# Generated by Django 5.1.6 on 2025-03-04 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renouvellement',
            fields=[
                ('renouvellement_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_demande', models.DateField()),
                ('date_renouvellement', models.DateField(null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], max_length=50)),
                ('commentaires', models.TextField(null=True)),
                ('documents_soumis', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours')),
            ],
            options={
                'db_table': 'renouvellement',
            },
        ),
    ]
