# Generated by Django 5.1.6 on 2025-03-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_email'),
    ]

    operations = [
    ]
