# Generated by Django 5.1.6 on 2025-03-07 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20250307_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='typeclient',
            options={'verbose_name': 'Type de client', 'verbose_name_plural': 'Types de clients'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='adresse_rue',
        ),
        migrations.RemoveField(
            model_name='client',
            name='autresnom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nomclient',
        ),
        migrations.AddField(
            model_name='client',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Client actif'),
        ),
        migrations.AddField(
            model_name='client',
            name='adresse_siege',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse du siège'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='client',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email de la personne de contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='fonction_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction de la personne de contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='nom_entite',
            field=models.CharField(default='À renseigner', max_length=100, verbose_name="Nom de l'entité"),
        ),
        migrations.AddField(
            model_name='client',
            name='personne_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Personne de contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='secteur_activite',
            field=models.CharField(choices=[('education', 'Éducation'), ('sante', 'Santé'), ('agriculture', 'Agriculture'), ('technologie', 'Technologie'), ('finance', 'Finance'), ('humanitaire', 'Humanitaire'), ('environnement', 'Environnement'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='client',
            name='sigle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigle/Acronyme'),
        ),
        migrations.AddField(
            model_name='client',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de la personne de contact'),
        ),
        migrations.AddField(
            model_name='typeclient',
            name='categorie',
            field=models.CharField(choices=[('ong', 'ONG'), ('sponsor', 'Sponsor'), ('entreprise', 'Entreprise'), ('autre', 'Autre')], default='autre', help_text='Catégorie principale du client', max_length=50),
        ),
        migrations.AddField(
            model_name='typeclient',
            name='description',
            field=models.TextField(blank=True, help_text='Description supplémentaire du type de client', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='localite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_immatriculation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'immatriculation/Enregistrement"),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone principal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='typeclientid',
            field=models.ForeignKey(db_column='typeclientid', on_delete=django.db.models.deletion.CASCADE, to='clients.typeclient', verbose_name='Type de client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
