# Generated by Django 5.1.6 on 2025-03-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_options_alter_typeclient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeclient',
            name='reseau',
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_entite',
            field=models.CharField(max_length=100, verbose_name="Nom de l'entité"),
        ),
    ]
