# Generated by Django 5.1.6 on 2025-03-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_typeclient_reseau_alter_client_nom_entite'),
        ('clients', '0006_initial_client_types'),
    ]

    operations = [
    ]
