# Generated by Django 5.1.6 on 2025-03-04 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_document', models.CharField(max_length=100)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('chemin_fichier', models.TextField()),
                ('date_soumission', models.DateField()),
                ('date_validation', models.DateField(null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('expire', 'Expiré')], max_length=50)),
                ('commentaires', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours')),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
