# Generated by Django 5.1.6 on 2025-03-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprenants', '0001_initial'),
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('resultat_id', models.AutoField(primary_key=True, serialize=False)),
                ('assiduite', models.DecimalField(decimal_places=2, help_text='Pourcentage de présence', max_digits=5)),
                ('evaluation_continue', models.JSONField(help_text='Résultats des évaluations continues')),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('statut_final', models.CharField(choices=[('reussite', 'Réussite'), ('echec', 'Échec'), ('abandon', 'Abandon')], max_length=20)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resultat',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('presence_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_presence', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('retard', models.IntegerField(default=0)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprenants.apprenant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seances.seance')),
            ],
            options={
                'db_table': 'presence',
            },
        ),
    ]
