# Generated by Django 5.1.6 on 2025-03-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presence',
        ),
    ]
