# Generated by Django 5.1.6 on 2025-03-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_alter_cours_statut_approbation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='horaire',
            field=models.CharField(choices=[('pendant_bureau', 'During office hours'), ('apres_bureau', 'After office hours'), ('weekend', 'Weekend')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cours',
            name='statut_approbation',
            field=models.CharField(choices=[('en_attente', 'Pending'), ('approuve', 'Approved'), ('refuse', 'Rejected'), ('expire', 'Expired')], default='en_attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='cours',
            name='type_cours',
            field=models.CharField(choices=[('formateur', 'Training for Trainer'), ('apprenant', 'Training for Learner'), ('court', 'Short Course'), ('long', 'Long Course')], max_length=50),
        ),
        migrations.CreateModel(
            name='SessionCours',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('formateur', models.CharField(max_length=200)),
                ('capacite_max', models.IntegerField()),
                ('nombre_inscrits', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cours.cours')),
            ],
            options={
                'verbose_name': 'Session de cours',
                'verbose_name_plural': 'Sessions de cours',
                'db_table': 'session_cours',
            },
        ),
    ]
