# Generated by Django 5.1.6 on 2025-03-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_alter_cours_horaire_alter_cours_statut_approbation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=50),
        ),
        migrations.DeleteModel(
            name='SessionCours',
        ),
    ]
