# Generated by Django 5.1.6 on 2025-03-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_cours_start_time_cours_status_delete_sessioncours'),
        ('formateurs', '0002_remove_formateur_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='formateurs',
            field=models.ManyToManyField(blank=True, related_name='cours_assignes', to='formateurs.formateur', verbose_name='Formateurs assignés'),
        ),
    ]
