# Generated by Django 5.1.6 on 2025-03-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_cours_formateurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='status',
        ),
    ]
