# Generated by Django 5.1.6 on 2025-03-04 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
        ('lieux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('seance_id', models.AutoField(primary_key=True, serialize=False)),
                ('horaires', models.CharField(choices=[('pendant_bureau', 'Pendant les heures de bureau'), ('apres_bureau', 'Après les heures de bureau'), ('weekend', 'Weekend')], max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours (live)'), ('termine', 'Terminé (completed)'), ('annule_avec_paiement', 'Annulé avec paiement'), ('annule_sans_paiement', 'Annulé sans paiement')], max_length=50)),
                ('nombre_places_total', models.IntegerField()),
                ('nombre_places_restantes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours')),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lieux.lieu')),
            ],
            options={
                'db_table': 'session',
            },
        ),
    ]
