# Generated by Django 5.1.6 on 2025-03-09 17:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_cours_formateurs'),
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seance',
            old_name='date_debut',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='horaires',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='nombre_places_restantes',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='nombre_places_total',
        ),
        migrations.AddField(
            model_name='seance',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='nombre_places',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='seance',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='seance',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='seance',
            name='cours',
        ),
        migrations.AlterField(
            model_name='seance',
            name='statut',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='seance',
            name='cours',
            field=models.ManyToManyField(related_name='seances', to='cours.cours'),
        ),
    ]
