# Generated by Django 5.1.6 on 2025-03-09 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_cours_formateurs'),
        ('seances', '0004_seance_places_reservees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='cours',
        ),
        migrations.AddField(
            model_name='seance',
            name='cours',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='cours.cours'),
        ),
    ]
