# Generated by Django 5.1.6 on 2025-03-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0005_fix_formateur_user_relations'),
        ('seances', '0005_remove_seance_cours_seance_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='formateurs',
            field=models.ManyToManyField(related_name='seances_assignees', to='formateurs.formateur', verbose_name='Formateurs assignés'),
        ),
    ]
