# Generated by Django 5.1.6 on 2025-03-18 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0005_fix_formateur_user_relations'),
        ('seances', '0006_seance_formateurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('absence_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_absence', models.DateField(verbose_name="Date de l'absence")),
                ('raison', models.CharField(choices=[('maladie', 'Maladie'), ('conge', 'Congé'), ('formation', 'Formation'), ('autre', 'Autre raison')], default='autre', max_length=50)),
                ('details', models.TextField(blank=True, null=True, verbose_name="Détails de l'absence")),
                ('est_remplace', models.BooleanField(default=False, verbose_name='Est remplacé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formateur_absent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='formateurs.formateur', verbose_name='Formateur absent')),
                ('formateur_remplacant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remplacements', to='formateurs.formateur', verbose_name='Formateur remplaçant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='seances.seance')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_absence'],
                'unique_together': {('seance', 'formateur_absent', 'date_absence')},
            },
        ),
    ]
