# Generated by Django 4.2.20 on 2025-03-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0007_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='duree',
            field=models.IntegerField(default=1, help_text='Durée de la séance en heures', verbose_name='Durée (heures)'),
        ),
    ]
