# Generated by Django 4.2.20 on 2025-03-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0008_seance_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='duree',
            field=models.IntegerField(default=1, help_text='Durée de la séance en mois', verbose_name='Durée (mois)'),
        ),
    ]
