# Generated by Django 5.1.6 on 2025-03-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('lieuid', models.AutoField(primary_key=True, serialize=False)),
                ('lieu', models.CharField(max_length=100)),
                ('adresse', models.TextField(null=True)),
                ('personne_contact', models.CharField(max_length=100, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'lieu',
            },
        ),
    ]
