# Generated by Django 5.1.6 on 2025-03-05 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprenants', '0001_initial'),
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('presence_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_presence', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('retard', models.IntegerField(default=0)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprenants.apprenant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seances.seance')),
            ],
            options={
                'db_table': 'presence',
            },
        ),
    ]
