# Generated by Django 5.1.6 on 2025-03-29 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0003_alter_apprenant_niveau_academique'),
        ('clients', '0007_merge_20250308_0026'),
        ('inscriptions', '0001_initial'),
        ('seances', '0007_absence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='apprenants.apprenant'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='seances.seance'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_sponsorisees', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut_inscription',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='en_cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='type_inscription',
            field=models.CharField(choices=[('individuelle', 'Individuelle'), ('groupe', 'Groupe'), ('entreprise', 'Entreprise'), ('rse', 'RSE'), ('ong', 'ONG')], default='individuelle', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
