# Generated by Django 5.1.6 on 2025-03-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='categorie_age',
            field=models.CharField(choices=[('16-30', '16-30 years'), ('31-60', '31-60 years'), ('60+', 'Over 60 years')], max_length=20),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='niveau_academique',
            field=models.CharField(choices=[('sous_certificat', 'Below school certificate'), ('certificat', 'School certificate'), ('superieur', 'Above certificate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='sexe',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Other')], max_length=1),
        ),
    ]
