# Generated by Django 5.1.6 on 2025-03-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0002_alter_apprenant_categorie_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='niveau_academique',
            field=models.CharField(choices=[('below_certificate', 'Below High School'), ('high_school', 'High School Diploma'), ('higher_education', 'Higher Education')], max_length=50),
        ),
    ]
