# Generated by Django 5.1.6 on 2025-03-29 20:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0002_alter_inscription_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('paiement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_attente', 'En attente'), ('retard', 'En retard'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire'), ('carte', 'Carte de crédit/débit'), ('autre', 'Autre')], max_length=20, null=True)),
                ('reference', models.CharField(blank=True, help_text='Numéro de référence du paiement (ex: numéro de chèque)', max_length=100, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='inscriptions.inscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='PlanPaiement',
            fields=[
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_versements', models.PositiveIntegerField(default=1)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('intervalle_jours', models.PositiveIntegerField(default=30, help_text='Intervalle en jours entre les versements')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('complete', 'Complété'), ('annule', 'Annulé')], default='actif', max_length=20)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_paiement', to='inscriptions.inscription')),
            ],
            options={
                'verbose_name': 'Plan de paiement',
                'verbose_name_plural': 'Plans de paiement',
            },
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('rappel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_rappel', models.CharField(choices=[('automatique', 'Automatique'), ('manuel', 'Manuel')], default='automatique', max_length=20)),
                ('message', models.TextField()),
                ('envoye_a', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='paiements.paiement')),
            ],
            options={
                'verbose_name': 'Rappel de paiement',
                'verbose_name_plural': 'Rappels de paiement',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
