# Generated by Django 5.1.6 on 2025-03-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_paiementformateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rappel',
        ),
    ]
