# Generated by Django 5.1.6 on 2025-03-07 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0004_cours_start_time_cours_status_delete_sessioncours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('formateurid', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('specialites', models.TextField(verbose_name='Spécialités')),
                ('niveau_expertise', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('expert', 'Expert')], default='intermediaire', max_length=20, verbose_name="Niveau d'expertise")),
                ('type_formateur', models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe'), ('consultant', 'Consultant')], default='interne', max_length=20, verbose_name='Type de formateur')),
                ('cv', models.FileField(blank=True, null=True, upload_to='formateurs/cv/', verbose_name='CV')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='formateurs/photos/', verbose_name='Photo')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_conge', 'En congé')], default='actif', max_length=20, verbose_name='Statut')),
                ('disponibilite', models.TextField(help_text='Précisez les horaires de disponibilité', verbose_name='Disponibilité')),
                ('tarif_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarif horaire')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('cours', models.ManyToManyField(blank=True, related_name='formateurs', to='cours.cours', verbose_name='Cours assignés')),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
