# Generated by Django 5.1.6 on 2025-03-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='cours',
        ),
    ]
