# Generated by Django 5.1.6 on 2025-03-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0002_remove_formateur_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='specialites',
            field=models.TextField(blank=True, null=True, verbose_name='Spécialités'),
        ),
    ]
