# Generated by Django 5.1.6 on 2025-03-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0003_alter_formateur_specialites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='tarif_horaire',
        ),
    ]
